# В ЭТОМ ФАЙЛЕ ОТОБРАЗИМ настойки нашего демона по какой схеме он будет работать

# ЗДЕСЬ НАХОДИТСЯ ЭТАЛОННОЕ КОЛИЧЕСТВО ЗАПИСЕЙ ДЛЯ КАЖДОГО ТИПА ДАННЫХ
ArchInfo_settings = \
    {
        "ElConfig": 1,
        "PlsConfig": 1,
        "DigConfig": 1,
        "ElMomentEnergy": 840,
        "ElDayEnergy": 35,
        "ElMonthEnergy": 12,
        "ElDayConsEnergy": 35,
        "ElMonthConsEnergy": 12,
        "ElMomentQuality": 840,
        "ElArr1ConsPower": 1680,
        "PlsMomentPulse": 840,
        "PlsDayPulse": 35,
        "PlsMonthPulse": 12,
        "PlsHourPulse": 840,
        "DigMomentState": 840,
        "DigJournalState": 840,
        "ElJrnlPwr": 20,
        "ElJrnlTimeCorr": 20,
        "ElJrnlReset": 20,
        "ElJrnlC1Init": 20,
        "ElJrnlC2Init": 20,
        "ElJrnlTrfCorr": 20,
        "ElJrnlOpen": 20,
        "ElJrnlUnAyth": 20,
        "ElJrnlPwrA": 20,
        "ElJrnlPwrB": 20,
        "ElJrnlPwrC": 20,
        "ElJrnlProg": 20,
        "ElJrnlRelay": 20,
        "ElJrnlLimESumm": 20,
        "ElJrnlLimETrf": 20,
        "ElJrnlLimETrf1": 20,
        "ElJrnlLimETrf2": 20,
        "ElJrnlLimETrf3": 20,
        "ElJrnlLimETrf4": 20,
        "ElJrnlLimUAMax": 20,
        "ElJrnlLimUAMin": 20,
        "ElJrnlLimUBMax": 20,
        "ElJrnlLimUBMin": 20,
        "ElJrnlLimUCMax": 20,
        "ElJrnlLimUCMin": 20,
        "ElJrnlLimUABMax": 20,
        "ElJrnlLimUABMin": 20,
        "ElJrnlLimUBCMax": 20,
        "ElJrnlLimUBCMin": 20,
        "ElJrnlLimUCAMax": 20,
        "ElJrnlLimUCAMin": 20,
        "ElJrnlLimIAMax": 20,
        "ElJrnlLimIBMax": 20,
        "ElJrnlLimICMax": 20,
        "ElJrnlLimFreqMax": 20,
        "ElJrnlLimFreqMin": 20,
        "ElJrnlLimPwr": 20,
        "ElJrnlLimPwrPP": 20,
        "ElJrnlLimPwrPM": 20,
        "ElJrnlLimPwrQP": 20,
        "ElJrnlLimPwrQM": 20,
        "ElJrnlReverce": 20,
        "PlsJrnlTimeCorr": 20
    }
